# 1. Zero-shot GLiNER Biomedical Models
gliner-biomed-base-v1.0:
  display_name: "ihor/gliner-biomed-base-v1.0"
  model_path: "ihor/gliner-biomed-base-v1.0"
  is_trainable: false

gliner-biomed-large-v1.0:
  display_name: "ihor/gliner-biomed-large-v1.0"
  model_path: "ihor/gliner-biomed-large-v1.0"
  is_trainable: false

# 2. Zero-shot GLiNER2 Models
gliner2-base-v1:
  display_name: "fastino/gliner2-base-v1"
  model_path: "fastino/gliner2-base-v1"
  is_trainable: false

gliner2-large-v1:
  display_name: "fastino/gliner2-large-v1"
  model_path: "fastino/gliner2-large-v1"
  is_trainable: false

# 3. Zero-shot GLiNER2.5 Models
gliner2.5-base-v1:
  display_name: "fastino/gliner2.5-base-v1"
  model_path: "fastino/gliner2.5-base-v1"
  is_trainable: false
